### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by derkrasseleo** [studiorack/studiorack-app#9]
Windows 11, StudioRack v.0.0.31

I can't install any plugin except the ones that are in a .zip. After installing, the folders where the plugin should be are just empty.
One extreme case is dexed, where there is not even a folder for it:

![image](https://user-images.githubusercontent.com/16163571/166485361-547bc595-5375-49b2-9d47-8ee3ee235c36.png)

**Comment by kmturley** [comment]
This should be fixed in the latest release `v0.0.32`. StudioRack will download the installer into the StudioRack downloads directory for now. The rest of the installation process is manual.

I have not tested plugin installers properly (.exe and .msi) as I am planning to get rid of them. They create a poor user experience as the file is downloaded and then has to be manually clicked through by a user.

I am gradually going to converted all plugin installers over to .zip artifacts so that they can be extracted and copied to the the correct system directories without user intervention.

**Comment by derkrasseleo** [comment]
Great to see the progress! 
For some reason, studiorack still ignores the plugin directory, I'll open up a new issue for that
